### ISSUE TITLE
Ask for permission to include your code and use the rendered image

### ISSUE THREAD

**Issue by neozhaoliang** [SuperSodaSea/voxel-challenge-alpha#1]
Hi, thanks for participating in the challenge and also for your great artwork! May I ask for your permission to include your code in our voxel challenge repo:https://github.com/taichi-dev/voxel-challenge, and also the permission to use your rendered image on our official language webpage: https://www.taichi-lang.org/? We'd be very happy if having your permission and let more people know about the amazing things our taichi users have made. Thanks!

**Comment by SuperSodaSea** [comment]
@neozhaoliang No problem, use it freely :)

**Comment by neozhaoliang** [comment]
thanks！
